export const weatherFacts = [
  "Did you know the highest temperature ever recorded on Earth was 134°F (56.7°C) in Death Valley, USA?",
  "Lightning strikes about 100 times every second around the world.",
  "Raindrops can fall at speeds of up to 22 miles per hour.",
  "Snowflakes can take up to an hour to reach the ground.",
  "Hailstones can grow as large as baseballs in severe storms.",
  "Tornadoes can have winds exceeding 300 miles per hour.",
  "The coldest temperature ever recorded was −128.6°F (−89.2°C) in Antarctica.",
  "A single lightning bolt can contain up to 1 billion volts of electricity.",
  "Fog is made of tiny water droplets suspended in the air.",
  "The longest recorded lightning bolt stretched over 440 miles.",
  "A blizzard is defined as snow, wind, and low visibility for at least 3 hours.",
  "Some clouds weigh millions of pounds.",
  "The fastest wind gust recorded on Earth was 253 mph in Australia.",
  "Rainbows are actually full circles, but we usually see only an arc.",
  "Hurricanes can release the energy equivalent of 10,000 nuclear bombs.",
  "The ozone layer helps protect us from harmful UV rays.",
  "Tsunamis are often caused by underwater earthquakes.",
  "A snowflake has an average of 200 ice crystals.",
  "The wettest place on Earth is Mawsynram, India, with ~467 inches of rain annually.",
  "The driest place on Earth is the Atacama Desert in Chile.",
  "Some deserts can experience snow.",
  "The term 'weather' comes from the Old English word 'weder,' meaning air or storm.",
  "Thunder is caused by the rapid expansion of air due to lightning.",
  "A heatwave occurs when temperatures stay unusually high for several days.",
  "Microbursts are sudden, powerful downdrafts in thunderstorms.",
  "Sleet is ice pellets that form when raindrops freeze before hitting the ground.",
  "Freezing rain creates a glaze of ice on surfaces.",
  "The world's largest snowflake on record was 15 inches wide.",
  "Wind speeds are measured using an anemometer.",
  "Tornadoes are rated using the Enhanced Fujita Scale (EF0-EF5).",
  "The Coriolis effect causes winds and storms to rotate.",
  "A derecho is a widespread, long-lived windstorm associated with thunderstorms.",
  "The term 'barometer' comes from Greek words meaning 'weight' and 'measure'.",
  "The wet bulb temperature measures heat and humidity together.",
  "Heat index combines temperature and humidity to show how hot it feels.",
  "Wind chill combines temperature and wind speed to show how cold it feels.",
  "Some raindrops are not tear-shaped, but more like hamburger buns.",
  "Hailstorms are more common in the spring and summer months.",
  "Thunder can be heard up to 10 miles away from a storm.",
  "The eye of a hurricane is usually calm and clear.",
  "Weather balloons can reach altitudes of over 100,000 feet.",
  "Snow can be different colors, including pink and green, due to algae.",
  "The jet stream is a fast-flowing air current high in the atmosphere.",
  "The fastest tornado on record traveled 73 mph across the ground.",
  "Heat lightning is lightning too far away to hear thunder.",
  "Some clouds glow at night due to lightning inside them.",
  "Rain can contain dust and pollen from distant continents.",
  "Meteorologists use Doppler radar to track storms.",
  "Frost forms when water vapor freezes on cold surfaces.",
  "Hurricanes are called typhoons in the Pacific Ocean.",
  "The word 'monsoon' refers to seasonal wind patterns, not just rain.",
  "Fog can reduce visibility to near zero, causing dangerous conditions.",
  "A thundersnow is a snowstorm with lightning and thunder.",
  "Snow can insulate the ground and protect plants from freezing.",
  "Lake-effect snow occurs when cold air passes over warm lakes.",
  "The fastest wind recorded in a tornado was 318 mph.",
  "Some deserts experience extreme temperature swings between day and night.",
  "Cloud seeding can sometimes be used to encourage rainfall.",
  "Lightning can strike the same place twice.",
  "The Bermuda Triangle is famous for mysterious weather-related disappearances.",
  "The world’s largest hailstone weighed almost 2 pounds.",
  "Some animals can sense approaching storms.",
  "Weather satellites orbit the Earth to track storms and clouds.",
  "Rain can help clean the air by removing dust and pollen.",
  "Tropical cyclones form over warm ocean waters near the equator.",
  "A snowstorm in the Sahara Desert is a rare but recorded event.",
  "Ice storms can be more dangerous than snowstorms due to slick roads.",
  "A cumulonimbus cloud can reach heights of 39,000 feet or more.",
  "Some volcano eruptions can create their own weather patterns.",
  "The smell of rain is caused by a compound called petrichor.",
  "Meteorologists use supercomputers to predict weather patterns.",
  "The first weather satellite was launched in 1960.",
  "El Niño and La Niña are climate patterns that affect global weather.",
  "Thunderheads are tall, puffy clouds often associated with storms.",
  "A blizzard can produce zero visibility conditions.",
  "The world’s windiest city is Wellington, New Zealand.",
  "Some snowflakes are perfectly symmetrical, others are unique.",
  "Fog can sometimes appear colorful due to streetlights.",
  "Hurricane season in the Atlantic runs from June to November.",
  "Some regions experience 'lake-effect' freezing rain.",
  "Sandstorms can reduce visibility and cause respiratory problems.",
  "Weather can affect human mood and behavior.",
  "The largest recorded hailstone in diameter was 8 inches.",
  "Some clouds are called 'mammatus' due to their pouch-like shapes.",
  "Thunder can occur without rainfall if lightning is far away.",
  "Wind can shape sand dunes over time.",
  "Weather apps use complex models to predict local conditions.",
  "Some thunderstorms can last more than 12 hours.",
  "Lightning can strike water and conduct electricity over long distances.",
  "Snow can reflect sunlight and cause glare on bright days.",
  "Rainbows require sunlight and water droplets to appear.",
  "A temperature inversion can trap pollution in valleys.",
  "Some storms create a phenomenon called 'ball lightning.'",
  "Meteorologists use pressure systems to predict weather patterns.",
  "Some cloud formations indicate incoming severe weather.",
  "Thunderstorms are more frequent in summer due to heat and humidity.",
  "Hurricanes weaken when they move over cooler water or land.",
  "Weather affects agriculture, transport, and daily life globally.",
  "Some people can feel changes in atmospheric pressure as headaches.",
  "Weathering is the process by which weather affects rocks and soil.",
  "Snow can be compacted to form ice, which is harder to remove.",
  "Some deserts experience extreme flash floods after sudden rains.",
  "Wind speeds can be estimated using the Beaufort scale.",
  "The fastest rainfall ever recorded was 12 inches in 42 minutes."
];
